# Generated by Django 5.2.10 on 2026-01-31 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('response', models.JSONField(verbose_name='réponse')),
                ('ai_provider', models.CharField(default='anthropic', max_length=20, verbose_name='fournisseur IA')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='temps de traitement (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
