# Generated by Django 5.2.10 on 2026-01-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('testament', models.CharField(choices=[('OT', 'Ancien Testament'), ('NT', 'Nouveau Testament')], max_length=2, verbose_name='testament')),
                ('order', models.IntegerField(unique=True, verbose_name='ordre')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='abréviation')),
                ('chapter_count', models.IntegerField(verbose_name='nombre de chapitres')),
            ],
            options={
                'verbose_name': 'livre',
                'verbose_name_plural': 'livres',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='numéro')),
                ('verse_count', models.IntegerField(verbose_name='nombre de versets')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bible.book', verbose_name='livre')),
            ],
            options={
                'verbose_name': 'chapitre',
                'verbose_name_plural': 'chapitres',
                'ordering': ['book__order', 'number'],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='numéro')),
                ('text', models.TextField(verbose_name='texte')),
                ('version', models.CharField(default='LSG', max_length=10, verbose_name='version')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.chapter', verbose_name='chapitre')),
            ],
            options={
                'verbose_name': 'verset',
                'verbose_name_plural': 'versets',
                'ordering': ['chapter__book__order', 'chapter__number', 'number'],
                'unique_together': {('chapter', 'number', 'version')},
            },
        ),
    ]
